name: Build prod from release
on:
  create:
    tags:
      - "202[0-9][0-1][0-9][0-3][0-9]"
jobs:
  prod-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push latest image as prod
        run: ./.github/workflows/scripts/push_prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
