name: Build prod from release
on:
  release:
    types:
      - published
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Push latest image as prod
        run: ${{ github.action_path }}/scripts/push_prod.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
