name: Process master push
on:
  push:
    branches:
      - master
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker image from master and push it
        run: ${{ github.action_path }}/scripts/build_and_push_master.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}
