name: Build docker image from pull request
on:
  pull_request:
    branches:
      - master
jobs:
  pr-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build push latest image as prod
        run: ./.github/workflows/scripts/build_pull_request.sh
